### PR TITLE
Read system property before clearing it

### LINKED ISSUE #3120: Can't Host with new .9191
### My Operating System:
Win 10
### Engine version:
1.9.0.0.9191
### Map name and version:
N/A
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Try to host
### Do you have the exact error text? Please copy/paste if so
Error.java.lang.NullPointerException
```
TripleA engine version 1.9.0.0.9191
Feb 23, 2018 11:28:58 AM games.strategy.engine.chat.ChatController joinChat
INFO: Chatter:prastle port:3300 ip:24.53.234.237 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
Error: java.lang.NullPointerException
java.lang.NullPointerException
	at java.util.Hashtable.put(Unknown Source)
	at java.util.Properties.setProperty(Unknown Source)
	at java.lang.System.setProperty(Unknown Source)
	at games.strategy.engine.framework.startup.ui.InGameLobbyWatcher.newInGameLobbyWatcher(InGameLobbyWatcher.java:101)
	at games.strategy.engine.framework.startup.ui.ServerSetupPanel.createLobbyWatcher(ServerSetupPanel.java:75)
	at games.strategy.engine.framework.startup.ui.ServerSetupPanel.<init>(ServerSetupPanel.java:65)
	at games.strategy.engine.framework.startup.mc.SetupPanelModel.showServer(SetupPanelModel.java:55)
	at games.strategy.engine.framework.GameRunner.lambda$showMainFrame$3(GameRunner.java:285)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

### Instead of this error, what should have happened?
Host should open
### Any additional information that may help:
Can host fine with 1.9.0.0.8941

### PR DESCRIPTION
**Pull request by ssoloff**
Fixes #3120.

Regression caused by automated IDE refactoring in #3096.  This wasn't caught during review because the gap in the diff hid the call to `System#clearProperty()` that was in-between the old and new locations of the `System#getProperty()` call.

#### Testing

I verified starting a bot no longer results in the NPE reported in #3120.

### CODE REVIEW

**Comment by ssoloff** [comment]
The build errored due to a Travis network failure.  I restarted the failing job.

**Comment by DanVanAtta** [comment]
I appreciate the quick fix, but we've got a brittle code problem that is not fixed. Re-ordering lines should result in compilation errors, not runtime errors.  Why is the system property getting cleared at all? Could we just remove those and simplify?

**Comment by DanVanAtta** [comment]
> Regression caused by automated IDE refactoring in #3096. This wasn't caught during review because the gap in the diff hid the call to System#clearProperty() that was in-between the old and new locations of the System#getProperty() call.

Again, this type of catch is not the job of reviewer, it is job of PR author (me in that case) to do some smoke testing and job of unit tests to catch this.
