### PR TITLE
Checkstyle: Fix missing Javadoc violations indirectly (part 2)

### PR DESCRIPTION
**Pull request by ssoloff**
This PR fixes violations of the Checkstyle JavadocMethod rule.

The violations were fixed indirectly by either:

1. reducing the accessibility of the method from public to non-public if it was not used outside its package, or
1. removing the method if it was unused.

I purposefully avoided applying this technique to any method that may possibly be accessed via reflection (e.g. serialization and game XML parsing).  Please scrutinize the changes for any I may have mistakenly made that could break reflection as used by TripleA.

Due to the large number of violations that can be fixed using this technique, the fixes are being split over multiple PRs to keep the review size reasonable.

⚠️ Some changes in this PR **may** conflict with #1730 depending on its final state.  If #1730 looks like it will be merged relatively quickly, please merge it before this one, as the conflicts will be easier to fix on this branch.

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Java RMI is quite constraining. I hit this when testing while entering a network combat:
```
java.lang.NoSuchMethodError: games.strategy.engine.framework.ui.SaveGameFileChooser.getAutoSave2FileName()Ljava/lang/String;
	at games.strategy.engine.framework.ServerGame.autoSave(ServerGame.java:354)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:438)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:271)
	at games.strategy.engine.framework.startup.launcher.ServerLauncher$1.run(ServerLauncher.java:203)

```
host is running this branch, client master. The controllers I suspect are the non-compatible parts. 

NB: There have been some efforts to annotate methods wherever possible to identify what is used by serialization. Though that is not  a complete effort yet, so we still have to be careful around a number of classes. The 'Controller' and 'Delegate' classes tend to be the most heavily used via RMI.

Side note: automating a check for RMI + save game compatibility would be very useful. I would also just as well see us remove RMI and fix the save game compat issue, but for the short/medium term such an automation woudl be pretty valuable. In the meantime any change that is suspect needs to go through a good bit of testing. NB: Manual test process for compat is to launch a local network game as described above and entering combat, and connecting to the lobby usually catches most compat issues

**Comment by ssoloff** [comment]
@DanVanAtta, thanks for pointing this out.  I figured there were some serialization and/or reflection use cases I was not aware of.  However, I didn't expect it to occur with the UI. :smiley:

One question though...  I believe `SaveGameFileChooser#getAutoSave2FileName()` was removed as part of #1672, which I merged into this branch from `master` just before submitting the PR.  Is that the root cause of the above exception?  Is it possible your local `master` is behind the remote and doesn't have #1672?  The only thing I changed in `SaveGameFileChooser` in this PR was reducing the accessibility of the default constructor from public to private.  That shouldn't affect deserialization, as constructors of `Serializable` classes are not called during deserialization, right?

I attempted to reproduce the problem.  As suggested, I used this branch as the host.  First, I tried running build 4299 (latest release that includes #1672) as the client.  However, it did not freeze at the end of combat move.  Second, I tried running build 4291 (release immediately before #1672) as the client.  Once again, it did not freeze.  (Using both clients, I played through two complete player turns that both involved combat.)

I must be missing something in the repro steps.  Do you mind adding a few extra details to the above steps just in case I'm not doing something exactly right?  Does it depend on the map?  I used Iron Blitz 3rd Edition with the host playing Allies and the client playing Axis.

**Comment by DanVanAtta** [comment]
I rebased master latest and could no longer repro. Which does isolate to an existing commit on master. Thank you for pinpointing that.

File: src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcherWrapper.java [hunk 1]
```diff
@@ -30,12 +29,6 @@ public String getComments() {
     return lobbyWatcher == null ? "" : lobbyWatcher.getComments();
   }
 
-  public void setGame(final IGame game) {
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcherWrapper.java]: This method was introduced in 156e725, but there appears to never have been a call to it since.

File: src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcherWrapper.java [hunk 2]
```diff
@@ -59,11 +52,4 @@ public void setPassworded(final boolean passworded) {
       lobbyWatcher.setPassworded(passworded);
     }
   }
-
-  public GameDescription getGameDescription() {
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/framework/startup/ui/InGameLobbyWatcherWrapper.java]: The last call to this method was removed in ce2dd9d.

File: src/main/java/games/strategy/engine/framework/startup/ui/LocalSetupPanel.java [hunk 3]
```diff
@@ -146,15 +146,6 @@ public void update(final Observable o, final Object arg) {
     layoutComponents();
   }
 
-  public String getPlayerType(final String playerName) {
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/framework/startup/ui/LocalSetupPanel.java]: The last call to this method appears to have been removed in 6bf3caf (when this class was previously named `LocalPlayerSelectionPanel`).

File: src/main/java/games/strategy/engine/framework/startup/ui/PBEMSetupPanel.java [hunk 4]
```diff
@@ -431,15 +431,6 @@ public void propertyChange(final PropertyChangeEvent evt) {
     }
   }
 
-  public String getPlayerType(final String playerName) {
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/framework/startup/ui/PBEMSetupPanel.java]: This method was introduced in 8582401, but there appears to never have been a call to it since.

File: src/main/java/games/strategy/engine/lobby/server/userDB/MutedMacController.java [hunk 5]
```diff
@@ -124,39 +122,4 @@ public long getMacUnmuteTime(final String mac) {
     }
     return result;
   }
-
-  public List<String> getMacsThatAreStillMuted(final List<String> macs) {
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/lobby/server/userDB/MutedMacController.java]: This method was introduced in 225dcdd, but there appears to never have been a call to it since.

File: src/main/java/games/strategy/engine/lobby/server/userDB/MutedUsernameController.java [hunk 6]
```diff
@@ -125,39 +123,4 @@ public long getUsernameUnmuteTime(final String username) {
     }
     return result;
   }
-
-  public List<String> getUsernamesThatAreStillMuted(final List<String> usernames) {
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/lobby/server/userDB/MutedUsernameController.java]: This method was introduced in 5afd9f3, but there appears to never have been a call to it since.
